export const US_STATES = [
  { value: 'AL', label: 'Alabama' },
  { value: 'AK', label: 'Alaska' },
  { value: 'AZ', label: 'Arizona' },
  { value: 'AR', label: 'Arkansas' },
  { value: 'CA', label: 'California' },
  { value: 'CO', label: 'Colorado' },
  { value: 'CT', label: 'Connecticut' },
  { value: 'DE', label: 'Delaware' },
  { value: 'FL', label: 'Florida' },
  { value: 'GA', label: 'Georgia' },
  { value: 'HI', label: 'Hawaii' },
  { value: 'ID', label: 'Idaho' },
  { value: 'IL', label: 'Illinois' },
  { value: 'IN', label: 'Indiana' },
  { value: 'IA', label: 'Iowa' },
  { value: 'KS', label: 'Kansas' },
  { value: 'KY', label: 'Kentucky' },
  { value: 'LA', label: 'Louisiana' },
  { value: 'ME', label: 'Maine' },
  { value: 'MD', label: 'Maryland' },
  { value: 'MA', label: 'Massachusetts' },
  { value: 'MI', label: 'Michigan' },
  { value: 'MN', label: 'Minnesota' },
  { value: 'MS', label: 'Mississippi' },
  { value: 'MO', label: 'Missouri' },
  { value: 'MT', label: 'Montana' },
  { value: 'NE', label: 'Nebraska' },
  { value: 'NV', label: 'Nevada' },
  { value: 'NH', label: 'New Hampshire' },
  { value: 'NJ', label: 'New Jersey' },
  { value: 'NM', label: 'New Mexico' },
  { value: 'NY', label: 'New York' },
  { value: 'NC', label: 'North Carolina' },
  { value: 'ND', label: 'North Dakota' },
  { value: 'OH', label: 'Ohio' },
  { value: 'OK', label: 'Oklahoma' },
  { value: 'OR', label: 'Oregon' },
  { value: 'PA', label: 'Pennsylvania' },
  { value: 'RI', label: 'Rhode Island' },
  { value: 'SC', label: 'South Carolina' },
  { value: 'SD', label: 'South Dakota' },
  { value: 'TN', label: 'Tennessee' },
  { value: 'TX', label: 'Texas' },
  { value: 'UT', label: 'Utah' },
  { value: 'VT', label: 'Vermont' },
  { value: 'VA', label: 'Virginia' },
  { value: 'WA', label: 'Washington' },
  { value: 'WV', label: 'West Virginia' },
  { value: 'WI', label: 'Wisconsin' },
  { value: 'WY', label: 'Wyoming' },
  { value: 'DC', label: 'District of Columbia' },
];

export const COMFORT_LEVELS = [
  { value: 'very_comfortable', label: 'Very Comfortable - I can easily sleep overnight in a truck cab' },
  { value: 'comfortable', label: 'Comfortable - I can manage overnight stays' },
  { value: 'somewhat_comfortable', label: 'Somewhat Comfortable - Might need some adjustment time' },
  { value: 'prefer_stops', label: 'Prefer Stops - Would like regular rest stop breaks' },
];

export const RELATIONSHIPS = [
  { value: 'spouse', label: 'Spouse' },
  { value: 'parent', label: 'Parent' },
  { value: 'sibling', label: 'Sibling' },
  { value: 'child', label: 'Child' },
  { value: 'friend', label: 'Friend' },
  { value: 'relative', label: 'Other Relative' },
  { value: 'other', label: 'Other' },
];

export const CONDUCT_EXPECTATIONS = [
  {
    title: 'Professional Conduct',
    points: [
      'Maintain professional, respectful behavior at all times during the journey',
      'Refrain from using offensive, discriminatory, or inappropriate language',
      'Respect the personal space and property of the truck driver',
      'Follow all safety instructions provided by the driver',
    ],
  },
  {
    title: 'Prohibited Behaviors',
    points: [
      'No consumption of alcohol or illegal substances during the trip',
      'No smoking or vaping inside the truck cab unless explicitly permitted',
      'No engaging in any illegal activities during the journey',
      'No recording, photographing, or sharing content without explicit consent',
    ],
  },
  {
    title: 'Communication Standards',
    points: [
      'Report any safety concerns or emergencies immediately to the driver',
      'Maintain open and honest communication throughout the trip',
      'Notify emergency contacts and Road-Dogs of your status as required',
      'Participate in scheduled check-ins for safety monitoring',
    ],
  },
  {
    title: 'Liability Understanding',
    points: [
      'Acknowledge that you assume certain risks associated with long-distance travel',
      'Understand that Road-Dogs facilitates connections but is not liable for incidents during travel',
      'Agree to hold harmless the driver, carrier company, and Road-Dogs from claims',
      'Confirm you have adequate insurance coverage for the duration of travel',
    ],
  },
  {
    title: 'Relationship Boundaries',
    points: [
      'This is strictly a professional companion arrangement',
      'No romantic or sexual relationships are expected, implied, or permitted',
      'Both parties will respect personal boundaries at all times',
      'Any violation of these boundaries will result in immediate termination of the arrangement',
    ],
  },
];
